### ISSUE TITLE
[FEATURE] Add a new section about CONTEXT

### ISSUE THREAD

**Issue by leticiasilvazup** [ZupIT/ritchie-gitbook#29]
## What I would like to see

- A section explaining what is the CONTEXT and how it can be used on Ritchie.

A context allows to group credentials. For example like environments (production, staging, development). 

## What it is needed

- It would be a plus to add this information in the credential page, explaining about how to use it that way to ensure that no formula is ran with the wrong credentials.

**Comment by GuillaumeFalourd** [comment]
@leticiasilvazup , today we got the glossary with this explanation: https://docs.ritchiecli.io/glossary#context
Is that enough or would like to see examples using the context ?
