### ISSUE TITLE
Several directories should be merged and/or renamed

### ISSUE THREAD

**Issue by danilomarqueszup** [ZupIT/ritchie-gitbook#48]
## What I would like to see

Dirs to be merged under 'getting-started'
+ getting-started
+ geting-started
+ get-started

Dirs to be merged under 'software-architecture'
+ software-architecture
+ software-architecture-1

Dirs to be renamed
+ introducao -> introduction
+ resources-1 -> resources

## Why it is needed

It seems a cleanup in the directory structure is a good idea right now before the docs grow even more and the structure gets more confusing. As it is right now, the structure seems very prone to mistakes, with duplication of files, typos, etc.

**Comment by GuillaumeFalourd** [comment]
Hi @danilomarqueszup , thank you for the suggestion, we are working on it 👍

**Comment by danilomarqueszup** [comment]
Hey @GuillaumeFalourd, thanks for the reply! I'm ready to help as needed. Please feel free to ping me in Google Chat anytime.
