### ISSUE TITLE
2.1.0 [FEATURE] Update config.json section with new field REGEX

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-gitbook#53]
## What I would like to see

- Add config.json new field in documentation as related in this issue https://github.com/ZupIT/ritchie-cli/issues/513
- The section to update is this one: https://docs.ritchiecli.io/how-to/implement-a-formula

## Why it is needed

- A new field to configure inputs parameters is available and should be informed on the documentation.

## Details

- [x] PT - Branch v2.0-pt
- [x] EN - Branch ritchie-v2.0

**Comment by georgemayko** [comment]
I was taking a look on the repository, and realized the master is way behind another branches as ritchie-v2.0 for example.
Witch is the right branch to work?
About the languages, do we have to change more than one branch?

**Comment by GuillaumeFalourd** [comment]
Hi @georgemayko , thank you for your message.

You right, it's confusing as we didn't specified anything regarding the branches on our contributing file and we'll have to fix it.

To answer your question, at the moment our documentation is divided in 4 parts / branches :
- version 1 (EN) : master
- version 1 (PT) : doc-portuguese
- version 2 (EN) : ritchie-v2.0
- version 2 (PT) : v2.0-pt

This ISSUE would only be related to version 2 branches (ritchie-v2.0 and v2.0-pt)

**Comment by georgemayko** [comment]
I'll check docs on portuguese too. Just let me know if this one is ok.

**Comment by GuillaumeFalourd** [comment]
I've checked the PR for the english version and it's ok, thank you 👍

**Comment by georgemayko** [comment]
Just to know as this project has diferent branches for the language. I need to open a PR for each branch, isn't it?
I just saw task #52  and is pretty simular to this one and problably is on the same content of this issue.

**Comment by GuillaumeFalourd** [comment]
Yes, it would have to be a PR for each branch / language.
The #52 task has exactly the same context.
