### ISSUE TITLE
[FIX] Broken Links and configuration files examples

### ISSUE THREAD

**Issue by Gabrielgps25** [ZupIT/ritchie-gitbook#70]
Documentation contains some broken links and invalid files examples, e.g.:

* **CONTRIBUTING.md** contains a broken link to: https://docs.ritchiecli.io/community
* Pages [arquivo-config](https://docs.ritchiecli.io/v/v2.0-pt/tutorials/formulas/como-implementar-formulas/arquivo-config) (version 2 (PT)) and [config-file](https://docs.ritchiecli.io/tutorials/formulas/how-to-implement-a-formula/config-file) (version 2 (EN)) contains broken files examples, e.g.:
```json
{
      "condition": {
            variable: "rit_name",
            "operator": "!=",
            "value": "Dennis"
      }
      "label": "What is your date of birth?",
      "name": "rit_date_of_birth",
      "type": "text",
}
```

**Alert:** We need to investigate if we have another cases and fix all of them.

**Affected versions**: version 2 (EN), version 2 (PT).

**Comment by GuillaumeFalourd** [comment]
Hi @Gabrielgps25 , thank you for creating this ISSUE.

We corrected the pages your talked about and will update the broken link 👍🏼

**Comment by GuillaumeFalourd** [comment]
Broken link updated to https://docs.ritchiecli.io/faq#community 👍🏼
